# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fordable' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SmartDeviceLink', '~> 6.3.1'
  # Pods for fordable

  target 'fordableTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fordableUITests' do
    # Pods for testing
  end

end
